- name: install dependencies for nginx
  apt:
    name:
      - gnupg2
      - curl
      - ca-certificates
      - lsb-release
- name:
  shell: echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list

- name: Add official nginx signing key
  shell: curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
  args:
    warn: false

- name: Verify nignx proper key is configured
  shell: apt-key fingerprint ABF5BD827BD9BF62
  become: true

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install nginx
  apt:
    name: "{{ item }}"
  with_items:
    - nginx-common
    - nginx-full
    - lua5.2
    - lua5.2-doc
    - liblua5.2-dev
    - luajit
    - libnginx-mod-http-lua